// actionTypes.js
export const FETCH_ATTENDANCE = 'FETCH_ATTENDANCE';
export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const DELETE_ATTENDANCE = 'DELETE_ATTENDANCE';





// LeaveActionTypes.js

export const FETCH_LEAVES = 'FETCH_LEAVES';
export const ADD_LEAVE = 'ADD_LEAVE';
export const UPDATE_LEAVE = 'UPDATE_LEAVE';
export const DELETE_LEAVE = 'DELETE_LEAVE';
export const FETCH_ATTENDANCEE = 'FETCH_ATTENDANCEE';
export const ADD_ATTENDANCEE = 'ADD_ATTENDANCEE';

